image: maven:3.9-eclipse-temurin-17

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

karate_tests:
  stage: test
  script:
    - mvn clean test
  artifacts:
    when: always
    paths:
      - target/karate-reports/
      - target/cucumber-html-reports/
      - target/surefire-reports/
    expire_in: 1 week